### ISSUE TITLE
Possibly a bug but more likely i'm doing something wrong and it's not working. 

### ISSUE THREAD

**Issue by TheCableGuy99** [jorenn92/Maintainerr#1024]
**Describe the bug**
I'm not sure if this is a bug or something I'm doing wrong. I have a Plex folder called Movies-30-Day and I would like it to clear out any Movies after they have been added to Plex after 60 days (just to give family a little extra time to watch rather than 30 days). But it doesn't seem to be doing anything.

**To Reproduce**
Please see the screenshots for the rule I have setup to achieve the above.

**Expected behavior**
Delete movies from Radarr and Plex after 60 days they have been added to Plex.

**Screenshots**
![Screenshot 2024-04-07 202438](https://github.com/jorenn92/Maintainerr/assets/39552752/57ce134e-6f60-41de-a29a-9b1336ae4900)
![Screenshot 2024-04-07 202448](https://github.com/jorenn92/Maintainerr/assets/39552752/3a872cd7-23ae-4c76-a41d-ffa493cc9b39)

**Device (please complete the following information):**
 - OS: Synology Docker Containers
 - Version 2.0.3 Stable

**Additional context**
Nothing further to add.

**Comment by jorenn92** [comment]
Hey, 

It won't add anything because your rule checks if  'Plex add date' is later than 'Plex add date'. Which will never result in true, since it's exactly the same date. 

Want you want is this: 

![image](https://github.com/jorenn92/Maintainerr/assets/9069536/2bb7f291-d412-4f95-b955-0bb95a323cdf)

This will find all items that were added at least 60 days ago. 

'The take action after days' configuration value specifies how many days an item stays in the 'Movies 30-Day' collection before the actual removal happens. 

So when an item matches the rule, Maintainerr will add the item to the collection. This collection can be shown on the home page to notify your users. Once the item has lived in the collection for longer than the amount of days specified in 'take action after days', it'll remove the item.

**Comment by jorenn92** [comment]
> ahh this has created another issue now.
> 
> I subscribe to lists and radarr has automatically re-downloaded some of the ones removed.
> 
> Is it possible to add the removed ones to a radarr blacklist so they don't re-download?
> 
> Thanks for the help.

There’s a checkmark in the rule config ‘Add list exclusions’, that does what you want.
