### ISSUE TITLE
Setup on Synology / Docker

### ISSUE THREAD

**Issue by MichaelGoedken** [jorenn92/Maintainerr#1049]
**Describe the bug**
Running on Docker Synology DSM 7. I switched the network from bridge to host for Maintainerr, but I can't get it to run. When I start it on host, I get this message in a loop:

```
 ⨯ Failed to start server
Error: getaddrinfo ENOTFOUND maintainerr
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'maintainerr'
}

```
**To Reproduce**
```
docker run -d --name=maintainerr \
-p 6246:6246 \
-u 1026:100 \
-e TZ=America/Chicago \
-v /volume1/docker/maintainerr/config:/opt/data \
--restart always \
--net=host \
jorenn92/maintainerr:latest

```

**Comment by Sn3ider** [comment]
@jorenn92 I can run Maintainerr on DSM7, however when I add a custom UID and GID I got the following error:
Error: EACCES: permission denied, mkdir '/docker/maintainerr/.cache'

The user has access to these locations yet I got a permission denied. Even if I start the container with high privilege I have the same error. 
Any advice to setup a custom home location to save the config files so it won't disappear when a new update will be installed?

This happens when I change the HOME location to the mapped volume.

Thanks.

**Comment by jorenn92** [comment]
> @jorenn92 For some reason in normal network mode Maintainerr cannot talk to *arr apps that are also hosted on the Synology on the host network.

How are you connecting the apps? If Maintainerr isn't using the 'host' network but the other apps are, they should still be reachable using http://<server_ip>:<app_port>.

I've seen other reports where DSM7 Docker containers had issues with DNS name resolution. Perhaps that's also at play here?

**Comment by Sn3ider** [comment]
> ome reason in normal network mode Maintainerr cannot talk to *arr apps that are also hosted on the Synology on the host network.

What is the IP you are giving to Maintainerr to reach the normal network when you are using a bridge network? You have to call the gateway and not the normal network IP.
