### ISSUE TITLE
Dry Run?

### ISSUE THREAD

**Issue by nebb00** [jorenn92/Maintainerr#452]
Would it be possible to have a dry run option, so we can see what affect the rule will have? What media it will delete and maybe the raw stats to prove it's correct

**Comment by jorenn92** [comment]
Hi, thanks for testing Maintainerr! 

Maintainerr will not immediately delete your files. It will first add them to a temporary collection for x-duration (specified in parameter 'Media deleted after days')

You could always run your rules & check the collection. When you edit your rules, the collection will be removed and will only repopulate when the rule is run again. This is done because media might not be correct anymore due to changes you may have made.

The deletion will only take place when your media has been in the collection for longer than the specified amount of days.

You could simulate a dry run by executing rules & editing the rule after that to reset the collection. 

The statistic page is interesting. This will indeed be useful. 
However, it will take time to implement.
I'll go ahead and create a new task for this.

**Comment by nebb00** [comment]
My bad, i didn't understand before. While I have you, when you run your rule. Is it pretty quick? If I have no results immediately, i have no matches? Or does it take time to run?

**Comment by jorenn92** [comment]
No problem! There's no indication on the UI currently. But you can tail the log, there should be a line when starting & one when it's done.
```
LOG [CollectionWorkerService] Handling collection '<Your collection name>'
LOG [CollectionWorkerService] Handling collection '<Your collection name>' done
```

There's indeed a UI issue where duplicate entries are shown on the collection screen. This doesn't impact your Plex collection or collection handling, there's only 1 record, but for some reason the UI renders the card twice.

**Comment by nebb00** [comment]
Thanks. Just did a rule for rule for movies last viewed before 365 days, it returns 593. But tautulli reckons it should be 739.

Really not sure why the difference

**Comment by jorenn92** [comment]
That rule should contain all movies that have not been viewed in the last year. However, if the movie wasn't viewed at all, it won't be selected.

It's debatable that unseen movies should be selected by the rule. I'm not really sure how most people interpret it and if i should alter its behavior.  

To (hopefully) get what you want, you could try adding an 'OR' section with these 2 rules: 
- Plex - times viewed SMALLER than number 1
- And Plex - date added BEFORE 365 days

**Comment by estahn** [comment]
@jorenn92 I think this is not very clear to people. I was expecting some sort of dry-run. For rule creation some sort of preview would be very helpful, e.g. a list of movies/shows affected by the rule below.

**Comment by jorenn92** [comment]
A dry run doesn't really make sense because Maintainerr will only delete or unmonitor after the specified 'amount of days' has passed. Even if set to 1 day, you can freely edit and rerun the rule as many times as you like within that day. Any edit to the rules will reset the collection. Having a preview would, indeed, be beneficial.

**Comment by estahn** [comment]
@jorenn92 Cheers. After testing things I agree, the dry-run doesn't make. It's a user-experience issue imo. Initially I was under the impression the rules will delete media instantly. A text box explaining this behaviour in the app would reduce confusion.

**Comment by jorenn92** [comment]
Yeah, i agree. The UX can use some work. Not sure when i'll have time to improve it though.. I'm being overwhelmed with activity on this project.
