### ISSUE TITLE
[Question] Needs de-dupe and clean functionality

### ISSUE THREAD

**Issue by SirBastol** [jorenn92/Maintainerr#579]
Plex libraries that get bloated due to requests or conversion to diffrent resolutions  ..  
Need an automatic deduplication routine...   to remove those of the unwanted quality ( happens often when a 480p is found and then upgraded to 780 or higher in stages so you ahve several versions. 

and a way to void filess that have words like cam or screener and put them to remove first . 
 basically to be able to say i want my library to maintain the best version  only . . or  only 1080p or  wahtever version it finds that is not 1080p untill it gets a good 1080p version   etc.. 
 
 rules liek that . 
 
 automatically purgin  duplicate episodes  especially if in   multiples of same resolution  from diffrent sources  perhaps chosign which sources are preferred ( ie groups etc)  and to clean directories of all the *.nfo files etc.. when reneaming 
 
 if someone requests a  4k movie to deliver it but if the rule is to maintain 780 p or whatever  that  will be the version to keep once the requestor watches the 4k version  for example . .
 
 most labor intesive thing is to use the plex app and filter seearch by dupes  per episode on tv shows and delete   because often it willdownload a whole season just to get one missing episdoe . and you end up with  stacks of tv shows with duplicates and eating up hard drive space. 
 
  PLEASE   cleanarr doesnt work anymore  too many issue sand stillrequires manual intervention ( using plex is simpler at this point)  
  and the python script out there  are a run once thing and  often delete too much or too little  due to nto getting all teh info it needs form plex..  and then you ahve to remember to run it as that docker doenst run on a schedule
  
  this has a great interface and  would love to see it and overseer  become integrated to plex interface as a plug in .. where it can put colored frames around  posters wtih  like blue for has dupes  or grey for  requested but not in library ( may be avail on other plex accounts)  or to download it from other plex shares

**Comment by jorenn92** [comment]
Maintainerr is actually designed to remove entire movies, shows, seasons or episodes. It doesn't really look at the files behind the media. When a media item is removed, it'll remove all files associated with it. 

That doesn't mean it can't be an option in the future. But it's a big change, and that would take time. Time that I don't have atm.

Most of what you're requesting doesn't really sound like a task that should be handled by Maintainerr.
Radarr & Sonarr, when configured correctly, won't leave duplicates behind. These apps can be configured to prefer resolutions and groups and upgrade media until a given quality is reached. 
(If unsure about configuration: https://trash-guides.info/)

I think you should try to find a way to avoid the duplicates being created in the first place, instead of searching for tools to clean up the mess.

> this has a great interface and would love to see it and overseer become integrated to plex interface as a plug in .. where it can put colored frames around posters wtih like blue for has dupes or grey for requested but not in library ( may be avail on other plex accounts) or to download it from other plex shares

I never tried this, but maybe you can accomplish something like this with Plex Meta Manager. This app can add overlays (i.e. colored borders or tags) to media posters.

**Comment by SirBastol** [comment]
I agree with most of what you’re saying, but radar and sonar when they
upgrade they keep all previous downloads so if it happens to find a lower
quality first and then get a higher quality, it keeps both it doesn’t
actually remove the older one or the less resolution or whatever

I’ve checked and rechecked their settings and it definitely does not erase
old
There is a way to search in Plex for duplicates, which can create a nice
sorted list to be able to find them as Plex already knows all the
duplicates.

I just need a way to automatically select the one of the highest resolution
or the right rates of my overall preferences And prune down to just those
copies on demand.

Your maintainer should be able to do this without a huge amount of
difficulty if it can pull that search result from the API

I’m not a big knowledgeable person when it comes to the APIs, but I know
the generalities of it

And my coding skills are just not quite there for a job like this to add it
to get up and make up fork

So I’m hoping you understand what I say my request still stands, and it
would be great to have it in this application because maintaining your
library is kind of with the The name of your app


Even if we’re starters, it only kept the highest resolution, one or bit
rate one or lowest

Thanks for considering

**Comment by jorenn92** [comment]
Are you sure about this? I've been running Radarr & Sonarr for years, and they have always removed the old files after an upgrade.
When doing a quick google search, I can find people searching for methods to do the opposite (not deleting the file after an upgrade), but not what you're saying. 

Are you perhaps talking about the file in the download folder instead? If that file is still there, I could imagine *arr doesn't touch it. 

Creating a rule that returns the resolution / bitrate of the highest file and another one for media that has duplicate items should indeed be possible, but I'm not entirely sure what you would accomplish with them. If you'd create a rule with them, Maintainerr would just remove all files associated with that media item, so your high resolution one would be gone too.  

Changing Maintainerr to optionally look & handle files instead of whole media items is possible, but I'm not sure if that is what Maintainerr should do, since that's Radarr & Sonarr's territory.

**Comment by SirBastol** [comment]
Logically the Radarr and so are “upgrade”  should  remove    But it
doesn’t.   and no it’s not in the downloads

Radar and sonar just grab a higher quality version and add it to the pool.

It unmonitors ones you delete manuallly but there’s no anti duplication
rules I can find

This I have been wrestling with for months

If dupes were handled by them then things like cleanarr wouldn’t exist or
the python dockers scripts.  Which either do the same as Plex (give a list
with manual selections. Or need manual launching ) and are often wrong

Also they would only handle what was added by them.  And not bother with
existing dupes or  manual additions say added by handbrake

At least so far I have had no luck.

Ps I like your app. Even though it has an odd logic with wording.  I get
used to it


And like I said, when radar or sonar ads TV series, which is where I have
the biggest problem, it will sometimes grab a package of the entire season
just to fill one episode and then import the entire season.

I think this is where the duplication could be happening because it
doesn’tpay attention to anything but the one episode it’s trying to add
Yuen so I end up with 10 copies of the same episode imported.

Sorry I use text to speech so if some of this is typo and confusing, I just
can’t be bothered to auto incorrect, incorrect

**Comment by SirBastol** [comment]
[image: image.png]
given this result from plex after it has downloaded episodes..  there are
hundreds of dupes and currently the only way to remove them is to click
each one . press get info and look at the choice and remove  one or more
dupes... its often even the same resolutions due to the
aforementioned radar and sonar download methods that add them and they are
clearly not removing dupes

i just double checked and there is no  delete option in the upgrades . so
if you allow upgrades and it finds first a lower res one then later a
higher one it keeps both .. no removing of the old one..
and sometimes even still will download multiple high res ones depending on
listed bitrates in the filename . and keeps both    same in radarr  .
there is a delete option for propers and repacks  upgrades and it is
enabled but  is not the same thing

cleanarr  ( works sometimes  and other no .. its hit or miss)  but  it
still required you to go through the list and chose which ones to delete .
its not rule based
  just seems fitting for maintainerr to do the work    if plex knows the
bitrates etc  its a database query to make the dupe selection  and then
requery that subset  to select the lowest bitrates   prune and repeat the
search until there are no longer duplicates. .


Thank you ,
Paul Cole

*“Defeat is a state of mind. No one is ever defeated until defeat has been
accepted as reality. "*
*- Bruce Lee*

**Comment by SirBastol** [comment]
[image: image.png]

ideally i would like to set the library to maintain at  say 1080p or 720p (
for tv)   and only keep 4k versions  when overseer has requests for them
until they are watched and tehn  remove the higher bitrates  to conserve
space..  and remove the lower ones and the higher ones.to keep the library
at the specified rates..   but for now id be happy just to prune off lower
resolutions   and  such ..

this eats up tonnes of space on the drives that is unnecessary and takes
too much manual work to keep pruning daily ..  takes over two hours to
manually remove those 390 dupes  unless  i delete all versions of it and re
download.. potentially ending up with the same problem



Thank you ,
Paul Cole

*“Defeat is a state of mind. No one is ever defeated until defeat has been
accepted as reality. "*
*- Bruce Lee*

**Comment by jorenn92** [comment]
I don't really know what to say, this is the Radarr download / upgrade log from a random movie on my end: 
![Radarr upgrade log](https://github.com/jorenn92/Maintainerr/assets/9069536/519ecf4c-c5de-4ac4-a8bd-5ddc6469170d)

As you can see, it first downloaded a few 1080p versions, then upgrading to 2160p and finally settling on the best 2160p release, while always deleting the previous file.

Are you perhaps using torrents and are you seeding them from the same location? In that case, Radarr probably can't remove the file because the file is in use.

**Comment by SirBastol** [comment]
Well for whatever reason. That’s not the way mine works.  And I end up with
dupes

Yes I torrent. I dot. Have money to subscribe to groups

**Comment by Animosity022** [comment]
@SirBastol  - Your best bet would be to analyze why you are getting dupes and fix it. Sonarr/Radarr don't leave duplicates around unless there is a config/permission error. If both apps are doing it, that leads me to think your config is broken somewhere along the way.

**Comment by SirBastol** [comment]
Been checking it out. It’s mostly just sonarr.  Like I said it will get
full season bundles to fill one episode and end up with dupes.  And with
movies it upgrades but the old ones don’t get removed

**Comment by Animosity022** [comment]
Your best bet would be to ask on the forums for Sonarr/Radarr as that's something not rights. Logs would most likely tell you what's going on or why something cannot be deleted.
