### ISSUE TITLE
Instead of deleting the file, the counter starts going up

### ISSUE THREAD

**Issue by patheticaesthetic94** [jorenn92/Maintainerr#652]
I've been monitoring my first ever Maintainerr rule which has been slowly counting down from 30. 6 days ago, a whole bunch of movies SHOULD have been deleted from my server. Instead, nothing happened and the counter which would normally count down has started to count up. The number is now 6 as it has increased by 1 every day since the deletion was supposed to take place.

**To Reproduce**
1. Create a new rule to unmonitor and delete files and set up rules to pick up some movies
2. Wait for the movie to reach it's last day of activity before deletion
3. Check the next day to find the counter has gone up, rather than be deleted.

**Expected behavior**
The file should have been unmonitered and deleted from my file system.

**Screenshots**
<img width="1237" alt="Screenshot 2023-12-11 at 16 35 29" src="https://github.com/jorenn92/Maintainerr/assets/4212801/b8071e79-658d-4f5e-8d8b-17d41d8523b7">

**Device (please complete the following information):**
 - OS: Ubuntu
 - Version: 1.6.10

**Comment by jorenn92** [comment]
That's odd.. Is there anything in your container log that might indicate what happened? You could try tailing the log and manually running the collection handling. Perhaps it fails to connect to a service and skips the removal. (Maintainerr will only start the actual removal if all configured services are present)

I would think the UI badges would show -1, -2,.. in that case, but apparently not.

**Comment by sammydabammy** [comment]
`[Nest] 396  - 12/11/2023, 12:00:05 PM     LOG [CollectionsService] Removing media with id 14610 from collection..
/opt/server/dist/modules/collections/collection-worker.service.js:285
            const tvdbidPlex = plexData.Guid.find((el) => el.id.includes('tvdb'));
                                             ^
TypeError: Cannot read properties of undefined (reading 'find')
    at CollectionWorkerService.tvdbidFinder (/opt/server/dist/modules/collections/collection-worker.service.js:285:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CollectionWorkerService.handleMedia (/opt/server/dist/modules/collections/collection-worker.service.js:153:34)
    at async CollectionWorkerService.handle (/opt/server/dist/modules/collections/collection-worker.service.js:90:25)
Node.js v20.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2023-12-11 12:00:06,328 WARN exited: server (exit status 1; not expected)
2023-12-11 12:00:07,366 INFO spawned: 'server' with pid 411
yarn run v1.22.19
$ cd server && node dist/main
2023-12-11 12:00:08,699 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[Nest] 436  - 12/11/2023, 12:00:08 PM     LOG [NestFactory] Starting Nest application...
[Nest] 436  - 12/11/2023, 12:00:08 PM     LOG [PlexApiService] Plex API isn't fully initialized, required settings aren't set`

Is the issue because it can't find the same Movie / TV show inside of Radarr / Sonarr? There's also another line here about the Plex API not being fully initialised but I can confirm it is connected.

<img width="1244" alt="Screenshot 2023-12-11 at 17 34 37" src="https://github.com/jorenn92/Maintainerr/assets/4212801/7ac15f83-bebc-4b27-8e8b-3ce56dc471b9">

**Comment by jorenn92** [comment]
Looks like you managed to crash the server portion. Maintainerr expects something to be available in Plex’s metadata API response, but it’s not. I’ll try to fix it tomorrow

**Comment by sammydabammy** [comment]
Guess i'll need to wait as it seems I can't update to the 'develop' tag due to using arm64 processor rather than amd64

**Comment by jorenn92** [comment]
Oh, you’re actually the first person i speak to that’s using the arm64 tag. How does it run? 

I don’t test the arm64 image myself, since i don’t own a arm64 device.  But i’d love to find out if it has any flukes.

**Comment by sammydabammy** [comment]
Apart from this particular issue, I haven't noticed any problems with the tool! It seems to run as expected, but then again i've not had it long enough to know whether there are any further issues.
